on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    
    steps:
    - name: pull
      run: "cd /usr/share/nginx/html && git checkout main && git pull && exit"