on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    
    steps:
      
    - name: pull
      run: "cd ~/app/robshomelab && git checkout main && git pull && exit"