on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: pull repository
      run: "git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"