name: "Server Deployment"
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: nginx
    steps:
      - uses: actions/checkout@v4
      - name: say hello!
        run: echo "Hello there!"
