name: "Server Deployment"

on:

	push:

  	branches: [main]

jobs:

	deployment:

  	runs-on: ubuntu-latest

    steps:

    - uses: roberthallatt999/blog

    - name: Say Hello!

    run: echo "Hello there!"