name: "Server Deployment"
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: say hello!
        run: echo "Hello there. This is a test!"
      
      - name: Deploy code to Server

        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }}|base64 -d > ssh-key
          chmod 400 ssh-key
          ssh -i ssh-key -o StrictHostKeyChecking=no root@docker "cd /root/app/robshomelab && GIT_SSH_COMMAND='ssh -i /root/.ssh/ssh-key' git pull origin main"

    concurrency: 
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true